// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.XMLtoJSON
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("note")]
        public Note Note { get; set; }
    }

    public partial class Note
    {
        [JsonProperty("children")]
        public Child[] Children { get; set; }
    }

    public partial class Child
    {
        [JsonProperty("to", NullValueHandling = NullValueHandling.Ignore)]
        public Body To { get; set; }

        [JsonProperty("from", NullValueHandling = NullValueHandling.Ignore)]
        public Body From { get; set; }

        [JsonProperty("heading", NullValueHandling = NullValueHandling.Ignore)]
        public Body Heading { get; set; }

        [JsonProperty("body", NullValueHandling = NullValueHandling.Ignore)]
        public Body Body { get; set; }
    }

    public partial class Body
    {
        [JsonProperty("content")]
        public string Content { get; set; }
    }
}
